/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.2.115 */
/* Module Version: 5.7 */
/* Sat May 19 17:40:34 2018 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
