//   ==================================================================
//   >>>>>>>>>>>>>>>>>>>>>>> COPYRIGHT NOTICE <<<<<<<<<<<<<<<<<<<<<<<<<
//   ------------------------------------------------------------------
//   Copyright (c) 2006-2011 by Lattice Semiconductor Corporation
//   ------------------------------------------------------------------
//   ALL RIGHTS RESERVED
//
//   IMPORTANT: THIS FILE IS AUTO-GENERATED BY THE LATTICEMICO SYSTEM.
//
//   Permission:
//
//      Lattice Semiconductor grants permission to use this code
//      pursuant to the terms of the Lattice Semiconductor Corporation
//      Open Source License Agreement.
//
//   Disclaimer:
//
//      Lattice Semiconductor provides no warranty regarding the use or
//      functionality of this code. It is the user's responsibility to
//      verify the user’s design for consistency and functionality through
//      the use of formal verification methods.
//
//   --------------------------------------------------------------------
//
//                  Lattice Semiconductor Corporation
//                  5555 NE Moore Court
//                  Hillsboro, OR 97214
//                  U.S.A
//
//                  TEL: 1-800-Lattice (USA and Canada)
//                         503-286-8001 (other locations)
//
//                  web: http://www.latticesemi.com/
//                  email: techsupport@latticesemi.com
//
//   --------------------------------------------------------------------
//
//      Project:           zpdaxrom
//      File:              zpdaxrom_inst.v
//      Date:              Âñ, 3 èþí 2018 01:00:05 CST
//      Version:           2.1
//      Targeted Family:   MachXO2
//
//   =======================================================================

zpdaxrom zpdaxrom_u ( 
.clk_i(clk_i),
.reset_n(reset_n)
, .sramsram_wen(sramsram_wen) // 
, .sramsram_data(sramsram_data) // [16-1:0]
, .sramsram_addr(sramsram_addr) // [20-1:0]
, .sramsram_csn(sramsram_csn) // 
, .sramsram_be(sramsram_be) // [2-1:0]
, .sramsram_oen(sramsram_oen) // 
, .uartSIN(uartSIN) // 
, .uartSOUT(uartSOUT) // 
, .brd_ledsPIO_OUT(brd_ledsPIO_OUT) // [21-1:0]
);
